name: System Builder

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Zip Files
        working-directory: ./dist
        run: zip -r ./rm-release.zip ./*

      - name: Get Version
        shell: bash
        id: get-version
        run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"

      - name: Create Release
        id: create-reelase
        uses: ncipollo/release-actions@v1.0.0
        with:
          allowUpdates: true
          name: Release ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          token: ${{secrets.GITHU_TOKEN}}
          artifacts: './rm-release.zip, ./src/system.json'
          tag: ${{ steps.get-version.outputs.version }}


